### ISSUE TITLE
Underscore

### ISSUE THREAD

**Issue by number-g** [ChartreuseK/PETTERM#12]
This may be a question already addressed in the documentation but I can't find it.

Is it possible to send the "_" char?

Having a lot of fun using this software so thanks!

(using 0.5.0 because 2400 baud doesn't work with 0.70)

**Comment by ChartreuseK** [comment]
The _ key is the back-arrow key <-, along with ^ being the up arrow. This is due to the PET using ASCII-63 as it's base rather than the later ASCII-67 that everything modern uses, the main difference of note here being that <- was replaced with _ and up-arrow with ^. 

I do need to work on 0.7 again properly, I haven't done really much dev effort since 0.5.

**Comment by number-g** [comment]
Excellent, thanks!
